# Generated by Django 5.1.3 on 2024-12-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wallet_paper',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wallet_portfolio',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPaper',
            fields=[
                ('portfolio_paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.paper')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.portfolio')),
            ],
            options={
                'db_table': 'wallet_portfolio_paper',
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='papers_list',
            field=models.ManyToManyField(through='wallet.PortfolioPaper', to='wallet.paper'),
        ),
    ]
