# Generated by Django 5.1.3 on 2025-02-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='average_buy_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='current_price',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfoliopaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_papers', to='wallet.paper'),
        ),
        migrations.AlterField(
            model_name='portfoliopaper',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='wallet.portfolio'),
        ),
        migrations.AlterModelTable(
            name='portfoliopaper',
            table=None,
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('buy', models.BooleanField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.paper')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.portfolio')),
                ('portfolio_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.portfoliopaper')),
            ],
        ),
    ]
