# Generated by Django 5.1.3 on 2025-02-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_paper_options_portfoliopaper_average_buy_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paper',
            table='CMC_INFO',
        ),
    ]
