# Generated by Django 5.1.3 on 2025-04-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
        ('wallet', '0003_alter_paper_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='paper',
        ),
        migrations.AlterField(
            model_name='portfoliopaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_papers', to='charts.cmcinfo'),
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='papers_list',
            field=models.ManyToManyField(through='wallet.PortfolioPaper', to='charts.cmcinfo'),
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
