# Generated by Django 5.1.3 on 2025-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_transactions_paper_alter_portfoliopaper_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopaper',
            name='average_sell_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='buy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='realized_profit_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='sell_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='total_profit_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfoliopaper',
            name='unrealized_profit_loss',
            field=models.FloatField(default=0.0),
        ),
    ]
