# Generated by Django 5.1.3 on 2025-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_portfoliopaper_average_sell_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
