# Generated by Django 5.1.3 on 2025-04-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMCInfo',
            fields=[
                ('cmc_rank', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('symbol', models.TextField(default='')),
                ('price', models.FloatField(default=0.0)),
                ('market_cap', models.FloatField(default=0.0)),
                ('market_cap_dominance', models.FloatField(default=0.0)),
                ('volume_24h', models.FloatField(default=0.0)),
                ('max_supply', models.FloatField(blank=True, default=0.0, null=True)),
                ('circulating_supply', models.FloatField(default=0.0)),
                ('total_supply', models.FloatField(default=0.0)),
                ('infinite_supply', models.BooleanField(default=False)),
                ('date_added', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('percent_change_1h', models.FloatField(default=0.0)),
                ('percent_change_24h', models.FloatField(default=0.0)),
                ('percent_change_7d', models.FloatField(default=0.0)),
                ('percent_change_30d', models.FloatField(default=0.0)),
                ('percent_change_90d', models.FloatField(default=0.0)),
                ('platforms', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'CMC_INFO_charts',
            },
        ),
        migrations.CreateModel(
            name='FollowList',
            fields=[
                ('list_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'follow_list_charts',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_name', models.CharField(max_length=20)),
                ('portfolio_tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'portfolio_charts',
            },
        ),
        migrations.CreateModel(
            name='FollowingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('percent_change_24h', models.FloatField(default=0.0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.cmcinfo')),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.followlist')),
            ],
            options={
                'db_table': 'following_paper_charts',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_paper', models.FloatField()),
                ('average_buy_price', models.FloatField()),
                ('average_sell_price', models.FloatField()),
                ('buy_count', models.FloatField()),
                ('sell_count', models.FloatField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.cmcinfo')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.portfolio')),
            ],
            options={
                'db_table': 'portfolio_paper_charts',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('count_of_transaction', models.FloatField()),
                ('transaction_type_buy', models.BooleanField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.cmcinfo')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.portfolio')),
            ],
            options={
                'db_table': 'transactions_charts',
            },
        ),
    ]
