# Generated by Django 5.1.3 on 2025-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('cmc_rank', models.IntegerField(primary_key=True, serialize=False)),
                ('coin_id', models.IntegerField(db_column='id')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('market_cap_dominance', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('max_supply', models.FloatField(blank=True, null=True)),
                ('circulating_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('infinite_supply', models.BooleanField()),
                ('date_added', models.DateTimeField()),
                ('tags', models.TextField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('percent_change_30d', models.FloatField()),
                ('percent_change_90d', models.FloatField()),
            ],
            options={
                'db_table': 'CMC_INFO',
                'managed': False,
            },
        ),
    ]
