# Generated by Django 5.1.3 on 2025-02-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.coin')),
            ],
        ),
    ]
