# Generated by Django 5.1.3 on 2025-04-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followingpaper',
            name='percent_change_24h',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='followingpaper',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
