# Generated by Django 5.1.3 on 2025-02-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='coin',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WatchlistCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.coin')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='charts.watchlist')),
            ],
        ),
    ]
