# Generated by Django 5.1.3 on 2025-04-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_followingpaper_percent_change_24h_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='followlist',
            table='follow_list_charts',
        ),
    ]
