# Generated by Django 5.1.3 on 2025-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_followlist_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmcinfo',
            name='platforms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
